"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Icon = require("react-bootstrap-icons");
var BirlikteAl = function () {
    return (React.createElement("div", { className: "row mt-3 p-3" },
        React.createElement("div", { className: "col-md-12" },
            React.createElement("div", { className: "row p-2 border", id: "birlikteAlSatir" },
                React.createElement("div", { className: "col-5" },
                    React.createElement("div", { className: "birlikteAlFotoAlan" },
                        React.createElement("img", { className: "birlikteAlFoto", src: require('./BirlikteAlImg/34867488.png'), alt: "xiomiNote8" })),
                    React.createElement("div", { className: "birlikteAlBaslikTopveFiyatlarAlan" },
                        React.createElement("div", { className: "birlikteAlBaslikAlan" },
                            React.createElement("span", { className: "birlikteAlBaslik h6" }, "Xiaomi Redmi Note 8 4GB/64GB Mavi Ak\u0131ll\u0131 Telefon")),
                        React.createElement("div", { className: "birlikteAlTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "birlikteAlTop" },
                                React.createElement("span", { className: "birlikteAlTopYazi" }, "%9 \u0130ndirim")),
                            React.createElement("div", { className: "birlikteAlFiyatlar" },
                                React.createElement("span", { className: "birlikteAlAsilFiyat" }, "2.999 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "birlikteAlIndirim" }, "3.099 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "birlikteAlIndirimliFiyat" }, "2.999 TL"))))),
                React.createElement("div", { className: "col-2" },
                    React.createElement("div", { id: "birlikteAlIconAlan" },
                        React.createElement(Icon.PlusLg, { size: 22, id: "birlikteAlIcon" }))),
                React.createElement("div", { className: "col-5" },
                    React.createElement("div", { className: "birlikteAlFotoAlan" },
                        React.createElement("img", { className: "birlikteAlFoto", src: require('./BirlikteAlImg/49290160.png'), alt: "xiomiNote8" })),
                    React.createElement("div", { className: "birlikteAlBaslikTopveFiyatlarAlan" },
                        React.createElement("div", { className: "birlikteAlBaslikAlan" },
                            React.createElement("span", { className: "birlikteAlBaslik h6" }, "Preo Tpu Case Xiaomi Redmi Note 8 Polikarbon Telefon K\u0131l\u0131f\u0131 \u015Eeffaf")),
                        React.createElement("div", { className: "birlikteAlTopveFiyatlar" },
                            React.createElement("div", { className: "birlikteAlTop" },
                                React.createElement("span", { className: "birlikteAlTopYazi" }, "%15 \u0130ndirim")),
                            React.createElement("div", { className: "birlikteAlFiyatlar" },
                                React.createElement("span", { style: { display: "none" }, className: "birlikteAlAsilFiyat" }),
                                React.createElement("span", { className: "birlikteAlIndirim" }, "49,90 TL"),
                                React.createElement("span", { className: "birlikteAlIndirimliFiyat" }, "42,41 TL")))))),
            React.createElement("div", { className: "row p-2 border border-top-0", id: "birlikteAlUcretSatir" },
                React.createElement("div", { className: "col-6", id: "birlikteAlUcretBilgileriSutun" },
                    React.createElement("div", { id: "birlikteAlUcretBilgileri" },
                        React.createElement("span", { id: "birlikteAlToplamUrun" },
                            "Toplam:",
                            React.createElement("b", { id: "birlikteAlToplamUrunSayi" }, " 2 (\u00DCr\u00FCn)")),
                        React.createElement("span", { id: "birlikteAlToplamKazanc" },
                            "Toplam\u00A0Kazanc\u0131n\u0131z:",
                            React.createElement("b", null, "\u00A07.49\u00A0TL")),
                        React.createElement("span", { id: "birlikteAlToplamKazancIndirim" }, "3.048,90 TL"),
                        React.createElement("span", { id: "birlikteAlToplamKazancIndirimliFiyat" }, "3.041,41 TL"))),
                React.createElement("div", { className: "col-6", id: "birlikteAlUcretBilgileriButonSutun" },
                    React.createElement("button", { type: "button", className: "btn btn-success", id: "birlikteAlButon" },
                        React.createElement("div", null,
                            React.createElement(Icon.CartFill, { id: "birlikteAlIcon2" })),
                        React.createElement("div", null,
                            React.createElement("span", { id: "birlikteAlYazi" }, "Birlikte Al"))))))));
};
exports.default = BirlikteAl;
//# sourceMappingURL=BirlikteAl.js.map