"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
require("./TeknikOzellikler.css");
require("./TeknikOzelliklerJs.js");
var TeknikOzellikler = function () {
    return (React.createElement("div", { className: "container" },
        React.createElement("div", { className: "row" },
            React.createElement("div", { className: "col-md-12", id: "teknikOzelliklerTabMenuSutun" },
                React.createElement("ul", { id: "teknikOzelliklerTabMenu" },
                    React.createElement("li", { className: "teknikOzelliklerTabMenuItem", id: "urunAciklamasi" },
                        React.createElement("a", { className: "teknikOzelliklerTabMenuLink" }, "\u00DCr\u00FCn A\u00E7\u0131klamas\u0131")),
                    React.createElement("li", { className: "teknikOzelliklerTabMenuItem", id: "teknikOzellikler" },
                        React.createElement("a", { className: "teknikOzelliklerTabMenuLink" }, "Teknik \u00D6zellikler")),
                    React.createElement("li", { className: "teknikOzelliklerTabMenuItem", id: "taksitSecenekleri" },
                        React.createElement("a", { className: "teknikOzelliklerTabMenuLink" }, "Taksit Se\u00E7enekleri"))),
                React.createElement("div", { id: "teknikOzelliklerIcerikKismi" },
                    React.createElement("div", { id: "urunAciklamasiIcerik" },
                        React.createElement("div", { id: "urunAciklamasiIcerikBaslikAlan" },
                            React.createElement("span", { className: "h3" }, "Xiaomi Redmi Note 8 4GB/64GB Mavi Ak\u0131ll\u0131 Telefon")),
                        React.createElement("div", { id: "urunAciklamasiIcerikYaziAlan" },
                            React.createElement("span", { id: "urunAciklamasiIcerikYaziSpan" }, "\u00DCr\u00FCn \u0130\u00E7eri\u011Fine Kulakl\u0131k Dahil De\u011Fildir."),
                            React.createElement("p", { id: "urunAciklamasiIcerikYaziParagraf" }, "48MP D\u00F6rtl\u00FC Kamera All Star 48MP AI d\u00F6rt kamera Qualcomm\u00AE Snapdragon\u2122 665 4000mAh y\u00FCksek kapasiteli pil Pop\u00FCler renklerde 2.5D cam kaplama Daha k\u00FC\u00E7\u00FCk ekran alt\u0131 bo\u015Fluk ve \u00E7er\u00E7eve %90 y\u00FCksek ekran-g\u00F6vde oran\u0131 48MP ultra y\u00FCksek \u00E7\u00F6z\u00FCn\u00FCrl\u00FCk Telefonun ekran \u00E7\u00F6z\u00FCn\u00FCrl\u00FC\u011F\u00FCn\u00FCn neredeyse 19 kat\u0131 \u00E7\u00F6z\u00FCn\u00FCrl\u00FCkte foto\u011Fraflar Uzaktaki posterleri net bir \u015Fekilde \u00E7\u0131karabilirsiniz 120\u00B0 bozulma \u00F6nleyici ultra geni\u015F a\u00E7\u0131l\u0131 kamera G\u00F6z al\u0131c\u0131 manzara foto\u011Fraflar\u0131 i\u00E7in daha geni\u015F g\u00F6r\u00FC\u015F Keyifli seyahatlerinizi kaydedin G\u00FCzelli\u011Finizi ortaya \u00E7\u0131kartan portreler Derinlik kameras\u0131 Ayarlanabilir arkaplan bulan\u0131kla\u015Ft\u0131rma Kalabal\u0131kta s\u0131yr\u0131lan \u015Faheserler \u00E7ekin 2cm makro lens En ince ayr\u0131nt\u0131y\u0131 bile yakalay\u0131n 13MP Kamera G\u00FCzelle\u015Ftirme filtreleri ile profesyonel portre \u00F6z\u00E7ekimleri Qualcomm\u00AE Snapdragon\u2122 665 Sekiz \u00E7ekirdekli i\u015Flemci Ola\u011Fan\u00FCst\u00FC oyun deneyimi 1217 s\u00FCper lineer hoparl\u00F6rler Y\u00FCksek sesten daha fazlas\u0131 \u2014 m\u00FCkemmel ses kalitesi Gizli \u00F6zellik: Otomatik Hoparl\u00F6r Temizleme"))),
                    React.createElement("div", { id: "teknikOzelliklerIcerik" },
                        React.createElement("table", { className: "table" },
                            React.createElement("tbody", null,
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloBaslik" },
                                        React.createElement("h5", null, "Paket \u0130\u00E7eri\u011Fi")),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Ekran boyutu")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "6.3 ''"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Pakete dahil kablolar")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "USB C Tipi"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "H\u0131zl\u0131 ba\u015Flang\u0131\u00E7 rehberi")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "Evet"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "AC sarma adapt\u00F6r")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "Evet"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { style: { borderBottom: "0" }, className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Kullan\u0131m k\u0131lavuzu")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "Evet"))),
                                    React.createElement("td", { style: { borderBottom: "0" } })),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloBaslik" },
                                        React.createElement("h5", null, "Ekran")),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Ekran boyutu")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "6.3 ''"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Ekran \u015Fekli")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "D\u00FCz"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Ekran t\u00FCr\u00FC")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "IPS"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "En boy oran\u0131")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "19.5:9"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Dokunmatik ekran")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "Evet"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Ekran cam t\u00FCr\u00FC")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "Gorilla Glass"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "G\u00F6r\u00FCnt\u00FClenen renk say\u0131s\u0131")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "16 milyon renk"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Piksel yo\u011Funlu\u011Fu")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "409 ppi"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Yerel a\u00E7\u0131 oran\u0131")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "19.5:9"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Ekran \u00E7\u00F6z\u00FCn\u00FCrl\u00FC\u011F\u00FC")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "2340 x 1080 Piksel"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloBaslik" },
                                        React.createElement("h5", null, "Kamera")),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Arka Kamera \u00C7\u00F6z\u00FCn\u00FCrl\u00FC\u011F\u00FC")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "48 MP"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "\u00D6n Kamera \u00C7\u00F6z\u00FCn\u00FCrl\u00FC\u011F\u00FC")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "13 MP"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "\u0130\u015Fletim sistemi yaz\u0131l\u0131m\u0131")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "Android 9.0"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "\u00D6n kamera tipi")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "Tek kamera"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Arka kamera tipi")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "D\u00F6rtl\u00FC kamera"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Desteklenen video formatlar\u0131")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "M4V, MKV, MP4, XVID"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Oto fokus")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "Evet"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloBaslik" },
                                        React.createElement("h5", null, "A\u011F\u0131rl\u0131k & Boyutlar")),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "A\u011F\u0131rl\u0131k")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "190 g"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Y\u00FCkseklik")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "158, 3 mm"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Geni\u015Flik")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "75, 3 mm"))),
                                    React.createElement("td", null)),
                                React.createElement("tr", null,
                                    React.createElement("td", { className: "teknikOzelliklerIcerikTabloYaziSutun" },
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAdAlan" },
                                            React.createElement("span", null, "Derinlik")),
                                        React.createElement("div", { className: "teknikOzelliklerIcerikYaziOzellikAlan" },
                                            React.createElement("span", null, "8, 35 mm"))),
                                    React.createElement("td", null))))),
                    React.createElement("div", { id: "taksitSecenekleriIcerik" },
                        React.createElement("div", { className: "row", id: "taksitSecenekleriIcerikSatir" },
                            React.createElement("div", { className: "col-md-4 pb-3" },
                                React.createElement("div", { className: "taksitSecenekleriIcerikFotoAlan" },
                                    React.createElement("img", { className: "taksitSecenekleriIcerikFoto", src: require('./TeknikOzelliklerImg/credit-card-Axess.png'), alt: "axessLogo" })),
                                React.createElement("div", { className: "taksitSecenekleriBaslikveYazilari" },
                                    React.createElement("div", { className: "taksitSecenekleriIcerikBasligi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TAKS\u0130T SAYISI")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "AYLIK TUTAR")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TOPLAM"))),
                                    React.createElement("div", { className: "taksitSecenekleriIcerikYazisi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "1")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL"))))),
                            React.createElement("div", { className: "col-md-4 pb-3" },
                                React.createElement("div", { className: "taksitSecenekleriIcerikFotoAlan" },
                                    React.createElement("img", { className: "taksitSecenekleriIcerikFoto", src: require('./TeknikOzelliklerImg/credit-card-Bonus.png') })),
                                React.createElement("div", { className: "taksitSecenekleriBaslikveYazilari" },
                                    React.createElement("div", { className: "taksitSecenekleriIcerikBasligi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TAKS\u0130T SAYISI")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "AYLIK TUTAR")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TOPLAM"))),
                                    React.createElement("div", { className: "taksitSecenekleriIcerikYazisi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "1")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL"))))),
                            React.createElement("div", { className: "col-md-4 pb-3" },
                                React.createElement("div", { className: "taksitSecenekleriIcerikFotoAlan" },
                                    React.createElement("img", { className: "taksitSecenekleriIcerikFoto", src: require('./TeknikOzelliklerImg/credit-card-Cardfinans.png') })),
                                React.createElement("div", { className: "taksitSecenekleriBaslikveYazilari" },
                                    React.createElement("div", { className: "taksitSecenekleriIcerikBasligi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TAKS\u0130T SAYISI")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "AYLIK TUTAR")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TOPLAM"))),
                                    React.createElement("div", { className: "taksitSecenekleriIcerikYazisi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "1")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL"))))),
                            React.createElement("div", { className: "col-md-4 pb-3" },
                                React.createElement("div", { className: "taksitSecenekleriIcerikFotoAlan" },
                                    React.createElement("img", { className: "taksitSecenekleriIcerikFoto", src: require('./TeknikOzelliklerImg/credit-card-World.png') })),
                                React.createElement("div", { className: "taksitSecenekleriBaslikveYazilari" },
                                    React.createElement("div", { className: "taksitSecenekleriIcerikBasligi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TAKS\u0130T SAYISI")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "AYLIK TUTAR")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TOPLAM"))),
                                    React.createElement("div", { className: "taksitSecenekleriIcerikYazisi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "1")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL"))))),
                            React.createElement("div", { className: "col-md-4 pb-3" },
                                React.createElement("div", { className: "taksitSecenekleriIcerikFotoAlan" },
                                    React.createElement("img", { className: "taksitSecenekleriIcerikFoto", src: require('./TeknikOzelliklerImg/credit-card-Bankkart.png') })),
                                React.createElement("div", { className: "taksitSecenekleriBaslikveYazilari" },
                                    React.createElement("div", { className: "taksitSecenekleriIcerikBasligi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TAKS\u0130T SAYISI")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "AYLIK TUTAR")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TOPLAM"))),
                                    React.createElement("div", { className: "taksitSecenekleriIcerikYazisi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "1")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL"))))),
                            React.createElement("div", { className: "col-md-4 pb-3" },
                                React.createElement("div", { className: "taksitSecenekleriIcerikFotoAlan" },
                                    React.createElement("img", { className: "taksitSecenekleriIcerikFoto", src: require('./TeknikOzelliklerImg/credit-card-Maximum.png'), alt: "maximumLogo" })),
                                React.createElement("div", { className: "taksitSecenekleriBaslikveYazilari" },
                                    React.createElement("div", { className: "taksitSecenekleriIcerikBasligi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TAKS\u0130T SAYISI")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "AYLIK TUTAR")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TOPLAM"))),
                                    React.createElement("div", { className: "taksitSecenekleriIcerikYazisi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "1")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL"))))),
                            React.createElement("div", { className: "col-md-4 pb-3" },
                                React.createElement("div", { className: "taksitSecenekleriIcerikFotoAlan" },
                                    React.createElement("img", { className: "taksitSecenekleriIcerikFoto", src: require('./TeknikOzelliklerImg/credit-card-Paraf.png'), alt: "parafLogo" })),
                                React.createElement("div", { className: "taksitSecenekleriBaslikveYazilari" },
                                    React.createElement("div", { className: "taksitSecenekleriIcerikBasligi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TAKS\u0130T SAYISI")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "AYLIK TUTAR")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "TOPLAM"))),
                                    React.createElement("div", { className: "taksitSecenekleriIcerikYazisi" },
                                        React.createElement("div", null,
                                            React.createElement("span", null, "1")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL")),
                                        React.createElement("div", null,
                                            React.createElement("span", null, "2.999 TL"))))))))))));
};
exports.default = TeknikOzellikler;
//# sourceMappingURL=TeknikOzellikler.js.map