"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Icon = require("react-bootstrap-icons");
var react_router_dom_1 = require("react-router-dom");
require("./Navbar.css");
var Navbar = function () {
    return (React.createElement(React.Fragment, null,
        React.createElement("nav", { className: "navbar sticky-top navbar-expand-lg navbar-dark bg-warning", id: "nav" },
            React.createElement("div", { className: "container" },
                React.createElement("button", { className: "navbar-toggler", type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#menuAc" },
                    React.createElement("span", { className: "navbar-toggler-icon" })),
                React.createElement("div", { className: "collapse navbar-collapse", id: "menuAc" },
                    React.createElement("ul", { id: "menu", className: "navbar-nav me-auto mb-2 mb-lg-0" },
                        React.createElement("div", { className: "nav-item", style: { borderRight: "1px solid white", height: "45px" } }),
                        React.createElement("li", { className: "nav-item dropdown" },
                            React.createElement("a", { className: "nav-link active ms-3 me-3", style: { cursor: "default" }, role: "button", id: "acilirmenu" }, "T\u00FCm \u00DCr\u00FCnler"),
                            React.createElement("ul", { id: "dropdown-menu", className: "dropdown-menu border border-1" },
                                React.createElement("li", null,
                                    React.createElement(react_router_dom_1.Link, { className: "dropdown-item", to: "/Telefon" },
                                        React.createElement(Icon.Phone, { className: "me-3" }),
                                        "Telefon")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", null,
                                    React.createElement("a", { className: "dropdown-item", href: "#" },
                                        React.createElement(Icon.Laptop, { className: "me-3" }),
                                        "Bilgisayar")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", null,
                                    React.createElement("a", { className: "dropdown-item", href: "#" },
                                        React.createElement(Icon.Tv, { className: "me-3" }),
                                        "Tv,Ses ve G\u00F6r\u00FCnt\u00FC Sistemleri")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", null,
                                    React.createElement("a", { className: "dropdown-item", href: "#" },
                                        React.createElement(Icon.House, { className: "me-3" }),
                                        "Beyaz E\u015Fya ve Ankastre")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", null,
                                    React.createElement("a", { className: "dropdown-item", href: "#" },
                                        React.createElement(Icon.Hammer, { className: "me-3" }),
                                        "Elektrikli Ev Aletleri ve Ya\u015Fam")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", null,
                                    React.createElement("a", { className: "dropdown-item", href: "#" },
                                        React.createElement(Icon.Heart, { className: "me-3" }),
                                        "Ki\u015Fisel Bak\u0131m Ve Sa\u011Fl\u0131k")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", null,
                                    React.createElement("a", { className: "dropdown-item", href: "#" },
                                        React.createElement(Icon.Controller, { className: "me-3" }),
                                        "Oyun Konsollar\u0131,Hobi ve E\u011Flence")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", null,
                                    React.createElement("a", { className: "dropdown-item", href: "#" },
                                        React.createElement(Icon.Camera, { className: "me-3" }),
                                        "Foto\u011Fraf Makinesi")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", null,
                                    React.createElement("a", { className: "dropdown-item", href: "#" },
                                        React.createElement(Icon.Briefcase, { className: "me-3" }),
                                        "Ofis Malzemeleri ve Mobilyalar\u0131")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", null,
                                    React.createElement("a", { className: "dropdown-item", href: "#" },
                                        React.createElement(Icon.Watch, { className: "me-3" }),
                                        "Aksesuarlar")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", null,
                                    React.createElement("a", { className: "dropdown-item", href: "#" },
                                        React.createElement(Icon.ShieldCheck, { className: "me-3" }),
                                        "Kurulum Destek Paketleri")))),
                        React.createElement("div", { className: "nav-link", style: { padding: "0px", borderLeft: "1px solid white", height: "45px" } }),
                        React.createElement("li", { className: "nav-item dropdown", id: "markalarLi" },
                            React.createElement("a", { className: "nav-link  active ms-3 me-3", href: "Markalar/Markalar.html", role: "button", id: "acilirmenu1" }, "Markalar"),
                            React.createElement("ul", { id: "dropdown-menu1", className: "dropdown-menu border border-1 border-left-0 border-right-0 col-md-12" },
                                React.createElement("li", null,
                                    React.createElement("span", { className: "text-muted ms-5", style: { cursor: "default" } }, "\u00D6ne \u00C7\u0131kan Markalar")),
                                React.createElement("li", null,
                                    React.createElement("hr", { className: "dropdown-divider" })),
                                React.createElement("li", { className: "marka ms-5", id: "apple" },
                                    React.createElement("figure", { className: "figure" },
                                        React.createElement("img", { src: require('./NavbarImg/logo_apple_19.webp'), className: "figure-img img-fluid" }),
                                        React.createElement("a", { href: "Markalar/Marka_Icerik/Apple.html", className: "nav-link" },
                                            React.createElement("figcaption", { className: "figure-caption text-center figcaption" }, "Apple")))),
                                React.createElement("li", { className: "marka" },
                                    React.createElement("figure", { className: "figure", id: "samsung" },
                                        React.createElement("img", { src: require('./NavbarImg/logo_samsung_19.webp'), className: "figure-img img-fluid" }),
                                        React.createElement("a", { href: "#", className: "nav-link" },
                                            React.createElement("figcaption", { className: "figure-caption text-center figcaption" }, "Samsung")))),
                                React.createElement("li", { className: "marka", id: "casper" },
                                    React.createElement("figure", { className: "figure" },
                                        React.createElement("img", { src: require('./NavbarImg/category_logo_casper.webp'), className: "figure-img img-fluid" }),
                                        React.createElement("a", { href: "#", className: "nav-link" },
                                            React.createElement("figcaption", { className: "figure-caption text-center figcaption" }, "Casper")))),
                                React.createElement("li", { className: "marka", id: "huawei" },
                                    React.createElement("figure", { className: "figure" },
                                        React.createElement("img", { src: require('./NavbarImg/category_logo_huawei.webp'), className: "figure-img img-fluid" }),
                                        React.createElement("a", { href: "#", className: "nav-link" },
                                            React.createElement("figcaption", { className: "figure-caption text-center figcaption" }, "Huawei")))),
                                React.createElement("li", { className: "marka", id: "preo" },
                                    React.createElement("figure", { className: "figure" },
                                        React.createElement("img", { src: require('./NavbarImg/logo_preo_19.webp'), className: "figure-img img-fluid" }),
                                        React.createElement("a", { href: "#", className: "nav-link" },
                                            React.createElement("figcaption", { className: "figure-caption text-center figcaption" }, "Preo")))),
                                React.createElement("li", { className: "marka", id: "bosch" },
                                    React.createElement("figure", { className: "figure" },
                                        React.createElement("img", { src: require('./NavbarImg/category_logo_bosch.webp'), className: "figure-img img-fluid" }),
                                        React.createElement("a", { href: "#", className: "nav-link" },
                                            React.createElement("figcaption", { className: "figure-caption text-center figcaption" }, "Bosch")))),
                                React.createElement("hr", { className: "dropdown-dvider" }),
                                React.createElement("li", { className: "text-center", id: "altmarkalar" },
                                    React.createElement("a", { href: "#", style: { color: "white !important" } },
                                        "                                            ",
                                        React.createElement("img", { src: require('./NavbarImg/category_logo_realme.webp'), className: "img-fluid" })),
                                    React.createElement("a", { href: "#", style: { color: "white!important" } },
                                        React.createElement("img", { src: require('./NavbarImg/monster_logo_200619.webp'), className: "img-fluid" })),
                                    React.createElement("a", { href: "#", style: { color: "white !important" } },
                                        React.createElement("img", { src: require('./NavbarImg/xiaomi_yeni_210415.webp'), className: "img-fluid" })),
                                    React.createElement("a", { href: "#", style: { color: " white!important" } },
                                        React.createElement("img", { src: require('./NavbarImg/category_logo_asus.webp'), className: "img-fluid " })),
                                    React.createElement("a", { href: "#", style: { color: " white !important" } },
                                        React.createElement("img", { src: require('./NavbarImg/logo_lg.webp'), className: " img-fluid " })),
                                    React.createElement("a", { href: "#", style: { color: "white !important" } },
                                        React.createElement("img", { src: require('./NavbarImg/category_logo_dyson.webp'), className: " img-fluid" })),
                                    React.createElement("a", { href: "#", style: { color: "white !important" } },
                                        React.createElement("img", { src: require('./NavbarImg/logo-philips.png'), className: " img-fluid", id: "philips" }))))),
                        React.createElement("div", { className: "nav-link ", style: { padding: "0px", borderRight: "1px solid white", height: "45px" } }),
                        React.createElement("li", { className: "nav-item " },
                            React.createElement(react_router_dom_1.Link, { className: "nav-link active ms-3 me-3", to: "/Hakkimizda" }, "Hakk\u0131m\u0131zda")),
                        React.createElement("div", { className: "nav-link", style: { padding: "0px", borderRight: " 1px solid white", height: "45px" } }),
                        React.createElement("li", { className: "nav-item" },
                            React.createElement("a", { className: "nav-link active ms-3 me-3", href: "#" }, "Outlet")),
                        React.createElement("div", { className: "nav-link", style: { padding: "0", borderRight: "1px solid white", height: "45px" } })),
                    React.createElement("div", { className: "d-flex", id: "flex" },
                        React.createElement("span", { className: "badge rounded-pill ", style: { fontSize: "20px", cursor: "pointer" }, "data-bs-target": "#uyeKayit", "data-bs-toggle": "modal", id: "uye ol" }, "\u00DCye Ol"),
                        React.createElement("span", { id: "uye", className: "badge bg-warning ms-4", style: { fontSize: "20px", cursor: "pointer" }, "data-bs-target": "#uyeGiris", "data-bs-toggle": "modal" },
                            React.createElement(Icon.PersonCircle, { style: { marginBottom: "5px" } }),
                            " \u00DCye Giri\u015Fi"))))),
        React.createElement("div", { className: "modal fade", id: "uyeKayit", "data-bs-backdrop": "static" },
            React.createElement("div", { className: "modal-dialog modal-dialog-scrollable modal-fullscreen" },
                React.createElement("div", { className: "modal-content" },
                    React.createElement("div", { className: "modal-header" },
                        React.createElement("h5", { className: "modal-title" }, "\u00DCyelik Kayd\u0131"),
                        React.createElement("button", { className: "btn-close", "data-bs-dismiss": "modal" })),
                    React.createElement("form", { className: "needs-validation modal-body", noValidate: true },
                        React.createElement("div", { className: "row g-3" },
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("label", { className: "form-label" }, "Ad"),
                                React.createElement("input", { type: "text", className: "form-control", placeholder: "Ad", required: true }),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez")),
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("label", { className: "form-label" }, "Soyad"),
                                React.createElement("input", { type: "text", className: "form-control", placeholder: "Soyad", required: true }),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez")),
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("label", { className: "form-label" }, "Email"),
                                React.createElement("input", { type: "email", className: "form-control", placeholder: "Mail", required: true }),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez")),
                            React.createElement("div", { className: "col-6" },
                                React.createElement("label", { className: "form-label" }, "Tc"),
                                React.createElement("input", { type: "number", className: "form-control", placeholder: "Tc No", required: true }),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez")),
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("label", { className: "form-label" }, "Parola"),
                                React.createElement("input", { type: "password", className: "form-control", placeholder: "Parola", required: true }),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez")),
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("label", { className: "form-label" }, "Parola Tekrar"),
                                React.createElement("input", { type: "password", className: "form-control", placeholder: "Parola", required: true }),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez")),
                            React.createElement("div", { className: "col-12" },
                                React.createElement("label", { className: "form-label" }, "Adres"),
                                React.createElement("textarea", { className: "form-control", style: { height: 200 }, placeholder: "Apartment, studio, or floor", required: true }),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez")),
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("label", { className: "form-label" }, "\u0130l"),
                                React.createElement("input", { type: "text", className: "form-control", required: true }),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez")),
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("label", { className: "form-label" }, "\u0130l\u00E7e"),
                                React.createElement("select", { className: "form-select", required: true },
                                    React.createElement("option", { disabled: true }, "\u0130l\u00E7e Se\u00E7iniz.."),
                                    React.createElement("option", null, "Beylikd\u00FCz\u00FC"),
                                    React.createElement("option", null, "B\u00FCy\u00FCk\u00E7ekmece"),
                                    React.createElement("option", null, "Silivri")),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez"))),
                        React.createElement("div", { className: "modal-footer" },
                            React.createElement("button", { className: "btn btn-danger", "data-bs-dismiss": "modal" }, "Geri"),
                            React.createElement("button", { className: "btn btn-success", type: "submit" }, "Kay\u0131t Ol")))))),
        React.createElement("div", { className: "modal fade", id: "uyeGiris", "data-bs-backdrop": "static" },
            React.createElement("div", { className: "modal-dialog modal-dialog-scrollable modal-fullscreen" },
                React.createElement("div", { className: "modal-content" },
                    React.createElement("div", { className: "modal-header" },
                        React.createElement("h5", { className: "modal-title" }, "\u00DCye Giri\u015F"),
                        React.createElement("button", { className: "btn-close", "data-bs-dismiss": "modal" })),
                    React.createElement("form", { className: "needs-validation text-center", style: { marginLeft: "34%" }, noValidate: true },
                        React.createElement("div", { className: "row g-3 mb-3" },
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("label", { className: "form-label" }, "Email"),
                                React.createElement("input", { type: "email", className: "form-control", placeholder: "Mail", required: true }),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez"))),
                        React.createElement("div", { className: "row g-3 mb-3" },
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("label", { className: "form-label" }, "Parola"),
                                React.createElement("input", { type: "password", className: "form-control", placeholder: "Parola", required: true }),
                                React.createElement("div", { className: "invalid-feedback" }, "Bu Alan Bo\u015F Ge\u00E7ilemez"))),
                        React.createElement("div", { className: "row g-3 mb-3" },
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("button", { className: "btn btn-outline-warning w-100", type: "submit" }, "Giri\u015F"))),
                        React.createElement("div", { className: "row g-3" },
                            React.createElement("div", { className: "col-md-6" },
                                React.createElement("button", { className: "btn btn-outline-danger w-100", "data-bs-dismiss": "modal" }, "Geri")))))))));
};
exports.default = Navbar;
//# sourceMappingURL=Navbar.js.map