"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Icon = require("react-bootstrap-icons");
var Filtreleme = function () {
    return (React.createElement("div", { className: "container mb-4", id: "filtre" },
        React.createElement("div", { className: "row" },
            React.createElement("div", { className: "col-6" },
                React.createElement("div", { className: "filtreDiv" },
                    React.createElement("button", { className: "filtreButon", "data-bs-target": "#modalFiltre", "data-bs-toggle": "modal" },
                        React.createElement("span", { className: "filtreYazi" }, "Filtrele"),
                        React.createElement(Icon.FunnelFill, { className: "filtreIcon" })),
                    React.createElement("div", { className: "modal fade", id: "modalFiltre" },
                        React.createElement("div", { className: "modal-dialog modal-dialog-scrollable modal-dialog-centered" },
                            React.createElement("div", { className: "modal-content" },
                                React.createElement("div", { className: "modal-header d-flex" },
                                    React.createElement("h4", { className: "modal-title ms-auto" }, "Telefon Fiyatlar\u0131 ve Modelleri"),
                                    React.createElement("button", { className: "btn-close", "data-bs-dismiss": "modal" })),
                                React.createElement("div", { className: "modal-body" },
                                    React.createElement("div", { className: "accordion", style: { backgroundColor: "white" } },
                                        React.createElement("div", { className: "accordion-item" },
                                            React.createElement("h2", { className: "accordion-header" },
                                                React.createElement("button", { className: "accordion-button collapsed", type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#kategoriler" },
                                                    React.createElement(Icon.TagsFill, { className: "categoriesIcon" }),
                                                    React.createElement("span", null, "KATEGOR\u0130LER"))),
                                            React.createElement("div", { id: "kategoriler", className: "accordion-collapse collapse" },
                                                React.createElement("div", { className: "accordion-body" },
                                                    React.createElement("a", { href: "#" },
                                                        "Cep Telefonu Aksesuarlar\u0131\u00A0",
                                                        React.createElement("span", null, "(1.399)")),
                                                    React.createElement("a", { href: "#" },
                                                        "K\u0131l\u0131f ve Koruyucular\u00A0",
                                                        React.createElement("span", null, "(845)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Kulakl\u0131klar\u00A0",
                                                        React.createElement("span", null, "(533)")),
                                                    React.createElement("a", { href: "#" },
                                                        "K\u0131l\u0131f ve Koruyucular\u00A0",
                                                        React.createElement("span", null, "(845)")),
                                                    React.createElement("a", { href: "#" },
                                                        "K\u0131l\u0131flar\u00A0",
                                                        React.createElement("span", null, "(473)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Ekran Koruyucular\u00A0",
                                                        React.createElement("span", null, "(360)")),
                                                    React.createElement("a", { href: "#" },
                                                        "\u015Earj Cihazlar\u0131\u00A0",
                                                        React.createElement("span", null, "(336)")),
                                                    React.createElement("a", { href: "#" },
                                                        "\u015Earj Kablolar\u0131\u00A0",
                                                        React.createElement("span", null, "(248)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Cep Telefonu\u00A0",
                                                        React.createElement("span", null, "(213)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Bluetooth Kulakl\u0131klar\u00A0",
                                                        React.createElement("span", null, "(202)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Kulak \u0130\u00E7i Kulakl\u0131k\u00A0",
                                                        React.createElement("span", null, "(192)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Discount Category\u00A0",
                                                        React.createElement("span", null, "(183)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Orange Category\u00A0",
                                                        React.createElement("span", null, "(183)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Android Telefonlar\u00A0",
                                                        React.createElement("span", null, "(149)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Kulak \u00DCst\u00FC Kulakl\u0131k\u00A0",
                                                        React.createElement("span", null, "(149)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Giyilebilir Teknoloji\u00A0",
                                                        React.createElement("span", null, "(139)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Ta\u015F\u0131nabilir \u015Earj Cihazlar\u0131\u00A0",
                                                        React.createElement("span", null, "(113)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Ara\u00E7 Kitleri\u00A0",
                                                        React.createElement("span", null, "(93)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Ak\u0131ll\u0131 Saatler\u00A0",
                                                        React.createElement("span", null, "(74)")),
                                                    React.createElement("a", { href: "#" },
                                                        "iPhone iOS Telefonlar\u00A0",
                                                        React.createElement("span", null, "(64)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Giyilebilir Teknoloji Aksesuarlar\u0131\u00A0",
                                                        React.createElement("span", null, "(32)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Ak\u0131ll\u0131 Bileklik\u00A0",
                                                        React.createElement("span", null, "(25)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Telsiz ve Masa\u00FCst\u00FC Telefonlar\u00A0",
                                                        React.createElement("span", null, "(17)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Masa\u00FCst\u00FC Telefonlar\u00A0",
                                                        React.createElement("span", null, "(17)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Dr. Teknolog\u00A0",
                                                        React.createElement("span", null, "(16)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Ekran Koruma Hizmeti\u00A0",
                                                        React.createElement("span", null, "(16)")),
                                                    React.createElement("a", { href: "#" },
                                                        "iPhone 12 Pro\u00A0",
                                                        React.createElement("span", null, "(12)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Nbo Ak\u0131ll\u0131 Telefon\u00A0",
                                                        React.createElement("span", null, "(9)")),
                                                    React.createElement("a", { href: "#" },
                                                        "iPhone SE\u00A0",
                                                        React.createElement("span", null, "(8)")),
                                                    React.createElement("a", { href: "#" },
                                                        "iPhone 12 Pro Max\u00A0",
                                                        React.createElement("span", null, "(8)")),
                                                    React.createElement("a", { href: "#" },
                                                        "iPhone 12 Mini\u00A0",
                                                        React.createElement("span", null, "(8)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Adapt\u00F6rler\u00A0",
                                                        React.createElement("span", null, "(8)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Selfie \u00C7ubu\u011Fu\u00A0",
                                                        React.createElement("span", null, "(6)")),
                                                    React.createElement("a", { href: "#" },
                                                        "iPhone XR\u00A0",
                                                        React.createElement("span", null, "(3)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Sanal Ger\u00E7eklik G\u00F6zl\u00FC\u011F\u00FC\u00A0",
                                                        React.createElement("span", null, "(3)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Bilgisayar\u00A0",
                                                        React.createElement("span", null, "(3)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Bilgisayar Aksesuarlar\u0131\u00A0",
                                                        React.createElement("span", null, "(2)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Kulakl\u0131klar\u00A0",
                                                        React.createElement("span", null, "(1)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Bluetooth Kulakl\u0131klar\u00A0",
                                                        React.createElement("span", null, "(1)")),
                                                    React.createElement("a", { href: "#" },
                                                        "Oppo Reno 5 Lite\u00A0",
                                                        React.createElement("span", null, "(1)"))))),
                                        React.createElement("div", { className: "accordion-item" },
                                            React.createElement("h2", { className: "accordion-header" },
                                                React.createElement("button", { className: "accordion-button collapsed", type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#markalar" },
                                                    React.createElement(Icon.StarFill, { className: "categoriesIcon" }),
                                                    React.createElement("span", null, "MARKALAR"))),
                                            React.createElement("div", { id: "markalar", className: "accordion-collapse collapse" },
                                                React.createElement("div", { className: "accordion-body" },
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "preoCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "preoCheck" },
                                                            "PREO\u00A0",
                                                            React.createElement("span", null, "(647)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "appleCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "appleCheck" },
                                                            "APPLE\u00A0",
                                                            React.createElement("span", null, "(202)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "samsungCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "samsungCheck" },
                                                            "SAMSUNG\u00A0",
                                                            React.createElement("span", null, "(181)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "ttecCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "ttecCheck" },
                                                            "TTEC\u00A0",
                                                            React.createElement("span", null, "(129)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "jblCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "jblCheck" },
                                                            "JBL\u00A0",
                                                            React.createElement("span", null, "(106)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "cellularlineCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "cellularlineCheck" },
                                                            "CELLULAR\u00A0LINE\u00A0",
                                                            React.createElement("span", null, "(95)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "huaweiCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "huaweiCheck" },
                                                            "HUAWEI\u00A0",
                                                            React.createElement("span", null, "(77)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "cellyCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "cellyCheck" },
                                                            "CELLY\u00A0",
                                                            React.createElement("span", null, "(64)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "ankerCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "ankerCheck" },
                                                            "ANKER\u00A0",
                                                            React.createElement("span", null, "(58)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "sonyCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "sonyCheck" },
                                                            "SONY\u00A0",
                                                            React.createElement("span", null, "(55)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "swissCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "swissCheck" },
                                                            "SWISS\u00A0",
                                                            React.createElement("span", null, "(41)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "xiaomiCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "xiaomiCheck" },
                                                            "XIAOMI\u00A0",
                                                            React.createElement("span", null, "(36)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "philipsCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "philipsCheck" },
                                                            "PHILIPS\u00A0",
                                                            React.createElement("span", null, "(32)")))))),
                                        React.createElement("div", { className: "accordion-item" },
                                            React.createElement("h2", { className: "accordion-header" },
                                                React.createElement("button", { className: "accordion-button collapsed", type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#fiyat" },
                                                    React.createElement(Icon.CurrencyDollar, { className: "categoriesIcon" }),
                                                    React.createElement("span", null, "F\u0130YAT"))),
                                            React.createElement("div", { id: "fiyat", className: "accordion-collapse collapse" },
                                                React.createElement("div", { className: "accordion-body" },
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "500Check" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "500Check" },
                                                            "500-1.000\u00A0TL\u00A0Aras\u0131\u00A0",
                                                            React.createElement("span", null, "(137)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "1000Check" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "1000Check" },
                                                            "1.000-2.500\u00A0TL\u00A0Aras\u0131\u00A0",
                                                            React.createElement("span", null, "(140)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "2500Check" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "2500Check" },
                                                            "2.500-4.000\u00A0TL\u00A0Aras\u0131\u00A0",
                                                            React.createElement("span", null, "(76)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "4000Check" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "4000Check" },
                                                            "4.000-5.500\u00A0TL\u00A0Aras\u0131\u00A0",
                                                            React.createElement("span", null, "(42)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "5500Check" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "5500Check" },
                                                            "5.500-7.500\u00A0TL\u00A0Aras\u0131\u00A0",
                                                            React.createElement("span", null, "(11)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "250Check" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "250Check" },
                                                            "250-500\u00A0TL\u00A0Aras\u0131\u00A0",
                                                            React.createElement("span", null, "(301)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "100Check" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "100Check" },
                                                            "100-250\u00A0TL\u00A0Aras\u0131\u00A0",
                                                            React.createElement("span", null, "(405)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "7500Check" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "7500Check" },
                                                            "7.500\u00A0TL\u00A0\u00DCzeri\u00A0",
                                                            React.createElement("span", null, "(73)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "50Check" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "50Check" },
                                                            "50-100\u00A0TL\u00A0Aras\u0131\u00A0",
                                                            React.createElement("span", null, "(749)"))),
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "50altiCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "50altiCheck" },
                                                            "50\u00A0TL\u00A0Alt\u0131\u00A0",
                                                            React.createElement("span", null, "(364)")))))),
                                        React.createElement("div", { className: "accordion-item" },
                                            React.createElement("h2", { className: "accordion-header" },
                                                React.createElement("button", { className: "accordion-button collapsed", type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#stok" },
                                                    React.createElement(Icon.BinocularsFill, { className: "categoriesIcon" }),
                                                    React.createElement("span", null, "STOK"))),
                                            React.createElement("div", { id: "stok", className: "accordion-collapse collapse" },
                                                React.createElement("div", { className: "accordion-body" },
                                                    React.createElement("div", { className: "form-check" },
                                                        React.createElement("input", { className: "form-check-input", type: "checkbox", id: "stokCheck" }),
                                                        React.createElement("label", { className: "form-check-label", htmlFor: "stokCheck" },
                                                            "Stoklu\u00A0\u00DCr\u00FCnler\u00A0",
                                                            React.createElement("span", null, "(2.226)")))))),
                                        React.createElement("div", { className: "p-3" },
                                            React.createElement("h1", { className: "h4" }, "Telefon"),
                                            React.createElement("p", null, "Hem en uygun fiyatl\u0131 hem son teknoloji telefon modelleri Teknosa'da! Telefon fiyatlar\u0131n\u0131 ve telefon \u00F6zelliklerini kar\u015F\u0131la\u015Ft\u0131r\u0131n, kullan\u0131c\u0131 yorumlar\u0131n\u0131 okuyun ve Teknosa g\u00FCvencesiyle sat\u0131n al\u0131n. Arad\u0131\u011F\u0131n\u0131z telefon sizi bekliyor!"))))))))),
            React.createElement("div", { className: "col-6" },
                React.createElement("div", { className: "filtreDiv" },
                    React.createElement("button", { className: "filtreButon", "data-bs-target": "#modalPopuler", "data-bs-toggle": "modal" },
                        React.createElement("span", { className: "filtreYazi" }, "Listeleme Se\u00E7enekleri"),
                        React.createElement(Icon.CardList, { className: "filtreIcon" })),
                    React.createElement("div", { className: "modal fade", id: "modalPopuler" },
                        React.createElement("div", { className: "modal-dialog modal-dialog-scrollable modal-dialog-centered" },
                            React.createElement("div", { className: "modal-content" },
                                React.createElement("div", { className: "modal-header d-flex" },
                                    React.createElement("h4", { className: "modal-title ms-auto" }, "Listeleme\u00A0Se\u00E7enekleri"),
                                    React.createElement("button", { className: "btn-close", "data-bs-dismiss": "modal" })),
                                React.createElement("div", { className: "modal-body", id: "listelemeModalBody" },
                                    React.createElement("button", { className: "listelemeButon", type: "button" },
                                        React.createElement(Icon.StarFill, { className: "listelemeIcon" }),
                                        React.createElement("span", null, "En Pop\u00FCler")),
                                    React.createElement("button", { className: "listelemeButon", type: "button" },
                                        React.createElement(Icon.SortAlphaDown, { className: "listelemeIcon" }),
                                        React.createElement("span", null, "\u0130sme G\u00F6re (A-Z)")),
                                    React.createElement("button", { className: "listelemeButon", type: "button" },
                                        React.createElement(Icon.SortAlphaUp, { className: "listelemeIcon" }),
                                        React.createElement("span", null, "\u0130sme G\u00F6re (Z-A)")),
                                    React.createElement("button", { className: "listelemeButon", type: "button" },
                                        React.createElement(Icon.SortNumericUpAlt, { className: "listelemeIcon" }),
                                        React.createElement("span", null, "Fiyata G\u00F6re (Artan)")),
                                    React.createElement("button", { className: "listelemeButon", type: "button" },
                                        React.createElement(Icon.SortNumericDownAlt, { className: "listelemeIcon" }),
                                        React.createElement("span", null, "Fiyata G\u00F6re (Azalan)")),
                                    React.createElement("button", { className: "listelemeButon", type: "button" },
                                        React.createElement(Icon.PiggyBankFill, { className: "listelemeIcon" }),
                                        React.createElement("span", null, "\u0130ndirimli \u00DCr\u00FCnler")))))))))));
};
exports.default = Filtreleme;
//# sourceMappingURL=Filtreleme.js.map