"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Marka = function () {
    return (React.createElement("div", { className: "row" },
        React.createElement("div", { className: "col-md-12" },
            React.createElement("div", { className: "card-group mt-5 urunKartgrubu" },
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "Telefon_Icerik/XiomiRedmi.html" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/34867488.png'), alt: "xiomiNote8" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8885287551026.png'), alt: "xiomilogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Xiaomi Redmi Note 8 4GB/64GB Mavi Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "2.999 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.099 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "2.999 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/38592535.png'), alt: "Huaweip40" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8876210815026.png'), alt: "huaweilogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Huawei P40 Lite 128 GB Pembe Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "3.599 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.099 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "2.999 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/31157116.jpg'), alt: "AppleAirpods" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8798552719410.png'), alt: "AppleAirPods" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Apple AirPods 2.Nesil ve \u015Earj Kutusu (MV7N2TU/A)"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "1.599 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.099 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "2.999 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/47008001.jpg'), alt: "SamsungGalaxyA30" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8798517788722.png'), alt: "Samsunglogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Samsung Galaxy A31 Blue Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { style: { display: "none" }, className: "card-text" }, "2.999 TL"),
                                React.createElement("span", { className: "card-text indirim" }, "3.099 TL"),
                                React.createElement("span", { className: "card-text indirimliFiyat" }, "2.999 TL")))))),
            React.createElement("div", { className: "card-group urunKartgrubu" },
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/38592258.png'), alt: "huaweip40lite128gb" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8876210815026.png'), alt: "huaweilogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Huawei P40 Lite 128 GB Siyah Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "3.599 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.099 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "2.999 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/35317881.jpg'), alt: "XiomiRedmiNote8" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8885287551026.png'), alt: "XiomiLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Xiaomi Redmi Note 8 4GB/128GB Siyah Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { style: { display: " none" }, className: "card-text" }, "3.599 TL"),
                                React.createElement("span", { className: "card-text indirim" }, "3.199 TL"),
                                React.createElement("span", { className: "card-text indirimliFiyat" }, "3.099 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/34867478.png'), alt: "XiomiRedmiNote8" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8885287551026.png'), alt: "XiomiLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Xiaomi Redmi Note 8 4GB/64GB Beyaz Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "2.999 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.099 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "2.999 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/38957997.jpg'), alt: "SamsungGalaxyNote10" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8798517788722.png'), alt: "Samsunglogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Samsung Galaxy Note10 Lite Siyah Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { style: { display: "none" }, className: "card-text" }, "2.999 TL"),
                                React.createElement("span", { className: "card-text indirim" }, "5.499 TL"),
                                React.createElement("span", { className: "card-text indirimliFiyat" }, "4.999 TL")))))),
            React.createElement("div", { className: "card-group urunKartgrubu" },
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/36158776.png'), alt: "SamsungGalaxyA51" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8798517788722.png'), alt: "SamsungLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Samsung Galaxy A51 Ak\u0131ll\u0131 Telefon Siyah"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%6")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { style: { display: "none" }, className: "card-text" }, "3.599 TL"),
                                React.createElement("span", { className: "card-text indirim" }, "3.499 TL"),
                                React.createElement("span", { className: "card-text indirimliFiyat" }, "3.299 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/35344786.jpg'), alt: "HuaweiWatchGt2" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8876210815026.png'), alt: "HuaweiLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Huawei Watch GT2 Latona-B19S Ak\u0131ll\u0131 Saat Siyah"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "1.399 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.199 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "3.099 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/38592532.png'), alt: "HuaweiP40Lite" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8876210815026.png'), alt: "HuaweLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Huawei P40 Lite 128 GB Ye\u015Fil Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "3.599 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.099 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "2.999 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/44167762.png'), alt: "HuaweiPSmart" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8876210815026.png'), alt: "HuaweiLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Huawei P Smart S 4-128GB Siyah Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%10")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { style: { display: "none" }, className: "card-text" }, "2.999 TL"),
                                React.createElement("span", { className: "card-text indirim" }, "2.899 TL"),
                                React.createElement("span", { className: "card-text indirimliFiyat" }, "2.599 TL")))))),
            React.createElement("div", { className: "card-group urunKartgrubu" },
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/27731024.jpg'), alt: "JblT500bt" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8798516215858.png'), alt: "JblLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Jbl T500BT Kulak \u00DCst\u00FC Mikrofonlu Kablosuz Kulakl\u0131k Siyah"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%21")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { style: { display: "none" }, className: "card-text" }, "3.599 TL"),
                                React.createElement("span", { className: "card-text indirim" }, "479 TL"),
                                React.createElement("span", { className: "card-text indirimliFiyat" }, "379 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/38592518.png'), alt: "HuaweiP40Lite" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8876210815026.png'), alt: "HuaweiLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Huawei P40 Lite E 64GB Siyah Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "2.799 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.199 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "3.099 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/36158757.png'), alt: "SamsungGalaxyA51" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8798517788722.png'), alt: "SamsungLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Samsung Galaxy A51 Ak\u0131ll\u0131 Telefon Pembe"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%6")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { style: { display: "none" }, className: "card-text" }, "3.599 TL"),
                                React.createElement("span", { className: "card-text indirim" }, "3.499 TL"),
                                React.createElement("span", { className: "card-text indirimliFiyat" }, "3.299 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/34920944.jpg'), alt: "AppleAirPodsPro" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8798552719410.png'), alt: "AppleLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Apple MWP22TU/A AirPods Pro Kulak \u0130\u00E7i Kablosuz Bluetooth Kulakl\u0131k"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%6")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "2.499 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.499 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "3.299 TL")))))),
            React.createElement("div", { className: "card-group urunKartgrubu" },
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/35317730.png'), alt: "XiomiRedmiNote8" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8885287551026.png'), alt: "XiomiLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Xiaomi Redmi Note 8 Pro 6GB/128GB Gri Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%21")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "3.699 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "479 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "379 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/35768115.png'), alt: "XiomiRedmiNote84Gb" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8885287551026.png'), alt: "XiomiLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Xiaomi Redmi Note 8 4GB/128GB Beyaz Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%9")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { style: { display: "none" }, className: "card-text" }, "2.799 TL"),
                                React.createElement("span", { className: "card-text indirim" }, "3.399 TL"),
                                React.createElement("span", { className: "card-text indirimliFiyat" }, "3.099 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/26932356.jpg'), alt: "JblT460bt" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8798516215858.png'), alt: "JblLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Jbl T460BT Kulak \u00DCst\u00FC Mikrofonlu Kablosuz Kulakl\u0131k Siyah"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%6")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "327 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.499 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "3.299 TL"))))),
                React.createElement("div", { className: "card urunKartlari" },
                    React.createElement("div", { className: "kartlarFotoAlan" },
                        React.createElement("a", { href: "javascript:void(0)" },
                            React.createElement("img", { className: "card-img-top kartlarFoto", src: require('./UrunlerImg/8806189203506_1562149528111.jpg'), alt: "HuaweiY62019" }))),
                    React.createElement("div", { className: "card-body kartlarBody" },
                        React.createElement("div", { className: "kartlarMarkaAlan" },
                            React.createElement("img", { className: "kartlarMarka", src: require('./UrunlerImg/marka/8876210815026.png'), alt: "HuaweiLogo" })),
                        React.createElement("div", { className: "kartlarUrunAdAlan" },
                            React.createElement("span", { className: "kartlarUrunAd" },
                                React.createElement("a", { href: "javascript:void(0)" }, "Huawei Y6 2019 Amber Brown Ak\u0131ll\u0131 Telefon"))),
                        React.createElement("div", { className: "kartlarTopveFiyatlar" },
                            React.createElement("div", { style: { display: "none" }, className: "kartlarTop" },
                                React.createElement("span", { className: "card-text kartTopYazi" }, "%6")),
                            React.createElement("div", { className: "kartlarFiyatlar" },
                                React.createElement("span", { className: "card-text" }, "1.849 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirim" }, "3.499 TL"),
                                React.createElement("span", { style: { display: "none" }, className: "card-text indirimliFiyat" }, "3.299 TL")))))))));
};
exports.default = Marka;
//# sourceMappingURL=Urunler.js.map