Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
require("./OdemeSecenekleri.css");
var OdemeSecenekleri = function () {
    return (React.createElement("div", { className: "container", id: "odemeAlanContainer" },
        React.createElement("div", { className: "row mt-5" },
            React.createElement("div", { className: "col-md-12" },
                React.createElement("span", { id: "odemeBaslik" }, "\u00D6deme Se\u00E7enekleri"))),
        React.createElement("div", { className: "row mt-4" },
            React.createElement("div", { className: "col-md-12 px-5", id: "odemeAlanSutun" },
                React.createElement("div", { id: "", className: "odemeAlan" },
                    React.createElement("div", { className: "odemeFoto", style: { backgroundImage: " url(" + require('./OdemeSecenekleriImg/credit-card-axess.webp') + ")" } }),
                    React.createElement("div", { className: "odemeYazi" },
                        React.createElement("span", null, "12 TAKS\u0130T"))),
                React.createElement("div", { className: "odemeBorder" }),
                React.createElement("div", { id: "", className: "odemeAlan" },
                    React.createElement("div", { className: "odemeFoto", style: { backgroundImage: " url(" + require('./OdemeSecenekleriImg/credit-card-world.webp') + ")" } }),
                    React.createElement("div", { className: "odemeYazi" },
                        React.createElement("span", null, "12 TAKS\u0130T"))),
                React.createElement("div", { className: "odemeBorder" }),
                React.createElement("div", { id: "", className: "odemeAlan" },
                    React.createElement("div", { className: "odemeFoto", style: { backgroundImage: " url(" + require('./OdemeSecenekleriImg/credit-card-paraf.webp') + ")" } }),
                    React.createElement("div", { className: "odemeYazi" },
                        React.createElement("span", null, "6 TAKS\u0130T"))),
                React.createElement("div", { className: "odemeBorder" }),
                React.createElement("div", { id: "", className: "odemeAlan" },
                    React.createElement("div", { className: "odemeFoto", style: { backgroundImage: " url(" + require('./OdemeSecenekleriImg/credit-card-bankkart.webp') + ")" } }),
                    React.createElement("div", { className: "odemeYazi" },
                        React.createElement("span", null, "4 TAKS\u0130T"))),
                React.createElement("div", { className: "odemeBorder" }),
                React.createElement("div", { id: "", className: "odemeAlan" },
                    React.createElement("div", { className: "odemeFoto", style: { backgroundImage: " url(" + require('./OdemeSecenekleriImg/credit-card-maximum.webp') + ")" } }),
                    React.createElement("div", { className: "odemeYazi" },
                        React.createElement("span", null, "4 TAKS\u0130T"))),
                React.createElement("div", { className: "odemeBorder" }),
                React.createElement("div", { id: "", className: "odemeAlan" },
                    React.createElement("div", { className: "odemeFoto", style: { backgroundImage: " url(" + require('./OdemeSecenekleriImg/credit-card-cardfinans.webp') + ")" } }),
                    React.createElement("div", { className: "odemeYazi" },
                        React.createElement("span", null, "3 TAKS\u0130T"))),
                React.createElement("div", { className: "odemeBorder" }),
                React.createElement("div", { id: "", className: "odemeAlan" },
                    React.createElement("div", { className: "odemeFoto", style: { backgroundImage: " url(" + require('./OdemeSecenekleriImg/credit-card-advantage.webp') + ")" } }),
                    React.createElement("div", { className: "odemeYazi" },
                        React.createElement("span", null, "3 TAKS\u0130T"))),
                React.createElement("div", { className: "odemeBorder" }),
                React.createElement("div", { id: "", className: "odemeAlan" },
                    React.createElement("div", { className: "odemeFoto", style: { backgroundImage: " url(" + require('./OdemeSecenekleriImg/credit-card-bonus.webp') + ")" } }),
                    React.createElement("div", { className: "odemeYazi" },
                        React.createElement("span", null, "3 TAKS\u0130T"))),
                React.createElement("div", { className: "odemeBorder" }),
                React.createElement("div", { id: "", className: "odemeAlan" },
                    React.createElement("div", { className: "odemeFoto", style: { backgroundImage: " url(" + require('./OdemeSecenekleriImg/mastercard-visa-logo.png') + ")" } }),
                    React.createElement("div", { className: "odemeYazi" },
                        React.createElement("span", null))),
                React.createElement("div", { className: "odemeBorder" })))));
};
exports.default = OdemeSecenekleri;
//# sourceMappingURL=OdemeSecenekleri.js.map