"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Icon = require("react-bootstrap-icons");
require("./UrunKategoriKurumsal.css");
var UrunKategoriKurumsal = function () {
    return (React.createElement("div", { className: "container" },
        React.createElement("div", { className: "row" },
            React.createElement("div", { className: "col-md-12 mt-4", id: "urun_kategoriSutun" },
                React.createElement("div", { className: "liste" },
                    React.createElement("h5", null, "Pop\u00FCler \u00DCr\u00FCnler"),
                    React.createElement("div", null),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "iPhone 12")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "iPhone 12 Pro")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "iPhone 11")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "iPhone 11 Pro Max")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "iPhone XR")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "iPhone SE")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Apple Watch Series 6")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Airpods 2")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Samsung Galaxy A71")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Samsung Galaxy Note 10 Lite")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Samsung Galaxy Note 20 Ultra")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Huawei P40 Lite")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Huawei P Smart Pro")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Huawei P Smart S")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Xiaomi Redmi Note 9 Pro")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Oppo Reno 3")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Oppo Reno 2Z")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Oppo Reno 4"))),
                React.createElement("div", { className: "liste" },
                    React.createElement("h5", null, "Kategoriler"),
                    React.createElement("div", null),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "PS5")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "XBox Series X")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "XBox Series S")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Ak\u0131ll\u0131 Telefon")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "iPhone")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Android Telefon")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Televizyon")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Notebook")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Oyun Bilgisayar\u0131 / Gaming Notebook")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Tablet")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "PS4")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "LED TV")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "S\u00FCp\u00FCrge")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Ak\u0131ll\u0131 Saat")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Apple Watch")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Ak\u0131ll\u0131 Bileklik")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Kulakl\u0131k")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Kablosuz Kulakl\u0131k")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Kahve Makinas\u0131")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "\u00C7ama\u015F\u0131r Makinas\u0131")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Klima")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Buzdolab\u0131")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Vantilat\u00F6r"))),
                React.createElement("div", { className: "liste" },
                    React.createElement("h5", null, "\u00D6zel Sayfalar"),
                    React.createElement("div", null),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Playstation 5")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Oyuncu Mouse ve Mouse Pad")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Asus Laptop")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Monster Notebook")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Xiaomi Cep Telefonu")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Samsung Cep Telefonu")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Huawei Cep Telefonu")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Oppo Cep Telefonu")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Macbook")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Apple Watch 6")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "\u00C7eyiz Seti")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Robot S\u00FCp\u00FCrge")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "T\u0131ra\u015F Makinesi")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Monit\u00F6r")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Epilasyon Aleti")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Harici Harddisk")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Bluetooth Hoparl\u00F6r")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Teknosa \u0130ndirim")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "\u00C7ay Makinesi"))),
                React.createElement("div", { className: "liste" },
                    React.createElement("h5", null, "Kurumsal"),
                    React.createElement("div", null),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Investor Relations")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "\u0130nsan Kaynaklar\u0131")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "\u0130\u015Flem Rehberi")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "\u0130leti\u015Fim")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Gizlilik S\u00F6zle\u015Fmesi")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Yat\u0131r\u0131mc\u0131 \u0130li\u015Fkileri")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Kurumsal Sat\u0131\u015F")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Ma\u011Fazalar\u0131m\u0131z")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Bilgi Toplumu Hizmetleri")),
                    React.createElement("div", null,
                        " ",
                        React.createElement("a", { href: "#" }, "Ki\u015Fisel Verilerin Korunmas\u0131"))),
                React.createElement("div", { className: "liste" },
                    React.createElement("h5", null, "Mobil Uygulamalar"),
                    React.createElement("div", null),
                    React.createElement("div", null,
                        React.createElement("a", { href: "#" },
                            React.createElement("img", { src: require('./UrunKategoriKurumsalImg/android.svg'), width: "130" }))),
                    React.createElement("div", null,
                        React.createElement("a", { href: "#" },
                            React.createElement("img", { src: require('./UrunKategoriKurumsalImg/ios.svg'), width: "130" }))),
                    React.createElement("div", null,
                        React.createElement("a", { href: "#" },
                            React.createElement("img", { src: require('./UrunKategoriKurumsalImg/appgallery.svg'), width: "130" }))),
                    React.createElement("div", null),
                    React.createElement("div", { className: "liste" },
                        React.createElement("h5", null, "Bizi Takip Edin"),
                        React.createElement("div", null),
                        React.createElement("div", null,
                            React.createElement("a", { href: "#" },
                                React.createElement(Icon.Facebook, { style: { fontSize: "20px" } }),
                                "Facebook")),
                        React.createElement("div", null,
                            React.createElement("a", { href: "#" },
                                React.createElement(Icon.Twitter, { style: { fontSize: "20px" } }),
                                "Twitter")),
                        React.createElement("div", null,
                            React.createElement("a", { href: "#" },
                                React.createElement(Icon.Linkedin, { style: { fontSize: "20px" } }),
                                "Linkedin")),
                        React.createElement("div", null,
                            React.createElement("a", { href: "#" },
                                React.createElement(Icon.Youtube, { style: { fontSize: "20px" } }),
                                "Youtube")),
                        React.createElement("div", null,
                            React.createElement("a", { href: "#" },
                                React.createElement(Icon.Instagram, { style: { fontSize: "20px" } }),
                                "\u0130nstagram")),
                        React.createElement("div", null,
                            React.createElement("a", { href: "#" },
                                React.createElement("img", { src: require('./UrunKategoriKurumsalImg/euronics-logo-large.png'), width: "130" })))))))));
};
exports.default = UrunKategoriKurumsal;
//# sourceMappingURL=UrunKategoriKurumsal.js.map