"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Icon = require("react-bootstrap-icons");
var Kategoriler = function () {
    return (React.createElement(React.Fragment, null,
        React.createElement("div", { className: "row p-2 border-bottom ", style: { borderColor: "rgb(180, 176, 176) !important" } },
            React.createElement("div", { className: "col-md-12" },
                React.createElement("span", { className: "display-6 text-muted" }, "Kategoriler"))),
        React.createElement("div", { className: "row" },
            React.createElement("div", { className: "col-md-12", style: { textAlign: "center" } },
                React.createElement("div", { id: "benimSlider\u0131m" },
                    React.createElement("div", { className: "TusDiv" },
                        React.createElement("span", { id: "geriKategori" },
                            React.createElement(Icon.ArrowBarLeft, null))),
                    React.createElement("div", { id: "sliderIc" },
                        React.createElement("div", { className: "topAlan" },
                            React.createElement("div", { className: "topAlanDiv" },
                                React.createElement("div", { className: "top", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.PhoneVibrate, { className: "kategoriIkon" })),
                                React.createElement("div", { className: "yazi" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Cep Telefonlar\u0131"))))),
                        React.createElement("div", { className: "topAlan" },
                            React.createElement("div", { className: "topAlanDiv" },
                                React.createElement("div", { className: "top", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Tv, { className: "kategoriIkon" })),
                                React.createElement("div", { className: "yazi" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Televizyonlar"))))),
                        React.createElement("div", { className: "topAlan" },
                            React.createElement("div", { className: "topAlanDiv" },
                                React.createElement("div", { className: "top", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Laptop, { className: "kategoriIkon" })),
                                React.createElement("div", { className: "yazi" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Notebook'lar"))))),
                        React.createElement("div", { className: "topAlan" },
                            React.createElement("div", { className: "topAlanDiv" },
                                React.createElement("div", { className: "top", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.House, { className: "kategoriIkon" })),
                                React.createElement("div", { className: "yazi" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Beyaz E\u015Fya"))))),
                        React.createElement("div", { className: "topAlan" },
                            React.createElement("div", { className: "topAlanDiv" },
                                React.createElement("div", { className: "top", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Hammer, { className: "kategoriIkon" })),
                                React.createElement("div", { className: "yazi" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Elektrikli Ev Aletleri"))))),
                        React.createElement("div", { className: "topAlan" },
                            React.createElement("div", { className: "topAlanDiv" },
                                React.createElement("div", { className: "top", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Heart, { className: "kategoriIkon" })),
                                React.createElement("div", { className: "yazi" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Ki\u015Fisel Bak\u0131m"))))),
                        React.createElement("div", { className: "topAlan" },
                            React.createElement("div", { className: "topAlanDiv" },
                                React.createElement("div", { className: "top", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Controller, { className: "kategoriIkon" })),
                                React.createElement("div", { className: "yazi" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Oyun Konsollar\u0131"))))),
                        React.createElement("div", { className: "topAlan" },
                            React.createElement("div", { className: "topAlanDiv" },
                                React.createElement("div", { className: "top", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Camera, { className: "kategoriIkon" })),
                                React.createElement("div", { className: "yazi" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Foto\u011Fraf Makineleri"))))),
                        React.createElement("div", { className: "topAlan" },
                            React.createElement("div", { className: "topAlanDiv" },
                                React.createElement("div", { className: "top", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Smartwatch, { className: "kategoriIkon" })),
                                React.createElement("div", { className: "yazi" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Aksesuar")))))),
                    React.createElement("div", { className: "TusDiv" },
                        React.createElement("span", { id: "ileriKategori" },
                            React.createElement(Icon.ArrowBarRight, null)))),
                React.createElement("div", { id: "benimSlider\u0131mMobil" },
                    React.createElement("div", { className: "TusDivMobil" },
                        React.createElement("span", { id: "geriKategoriMobil" },
                            React.createElement(Icon.ArrowBarLeft, null))),
                    React.createElement("div", { id: "sliderIcMobil" },
                        React.createElement("div", { className: "topAlanMobil" },
                            React.createElement("div", { className: "topAlanDivMobil" },
                                React.createElement("div", { className: "topMobil", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.PhoneVibrate, { className: "kategoriIkonMobil" })),
                                React.createElement("div", { className: "yaziMobil" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Cep Telefonlar\u0131"))))),
                        React.createElement("div", { className: "topAlanMobil" },
                            React.createElement("div", { className: "topAlanDivMobil" },
                                React.createElement("div", { className: "topMobil", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Tv, { className: "kategoriIkonMobil" })),
                                React.createElement("div", { className: "yaziMobil" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Televizyonlar"))))),
                        React.createElement("div", { className: "topAlanMobil" },
                            React.createElement("div", { className: "topAlanDivMobil" },
                                React.createElement("div", { className: "topMobil", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Laptop, { className: "kategoriIkonMobil" })),
                                React.createElement("div", { className: "yaziMobil" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Notebook'lar"))))),
                        React.createElement("div", { className: "topAlanMobil" },
                            React.createElement("div", { className: "topAlanDivMobil" },
                                React.createElement("div", { className: "topMobil", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.House, { className: "kategoriIkonMobil" })),
                                React.createElement("div", { className: "yaziMobil" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Beyaz E\u015Fya"))))),
                        React.createElement("div", { className: "topAlanMobil" },
                            React.createElement("div", { className: "topAlanDivMobil" },
                                React.createElement("div", { className: "topMobil", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Hammer, { className: "kategoriIkonMobil" })),
                                React.createElement("div", { className: "yaziMobil" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Elektrikli Ev Aletleri"))))),
                        React.createElement("div", { className: "topAlanMobil" },
                            React.createElement("div", { className: "topAlanDivMobil" },
                                React.createElement("div", { className: "topMobil", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Heart, { className: "kategoriIkonMobil" })),
                                React.createElement("div", { className: "yaziMobil" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Ki\u015Fisel Bak\u0131m"))))),
                        React.createElement("div", { className: "topAlanMobil" },
                            React.createElement("div", { className: "topAlanDivMobil" },
                                React.createElement("div", { className: "topMobil", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Controller, { className: "kategoriIkonMobil" })),
                                React.createElement("div", { className: "yaziMobil" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Oyun Konsollar\u0131"))))),
                        React.createElement("div", { className: "topAlanMobil" },
                            React.createElement("div", { className: "topAlanDivMobil" },
                                React.createElement("div", { className: "topMobil", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Camera, { className: "kategoriIkonMobil" })),
                                React.createElement("div", { className: "yaziMobil" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Foto\u011Fraf Makineleri"))))),
                        React.createElement("div", { className: "topAlanMobil" },
                            React.createElement("div", { className: "topAlanDivMobil" },
                                React.createElement("div", { className: "topMobil", onClick: function () { return window.location.href = '#'; } },
                                    React.createElement(Icon.Smartwatch, { className: "kategoriIkonMobil" })),
                                React.createElement("div", { className: "yaziMobil" },
                                    React.createElement("a", { href: "#" },
                                        React.createElement("span", null, "Aksesuar")))))),
                    React.createElement("div", { className: "TusDivMobil" },
                        React.createElement("span", { id: "ileriKategoriMobil" },
                            React.createElement(Icon.ArrowBarRight, null))))))));
};
exports.default = Kategoriler;
//# sourceMappingURL=Kategoriler.js.map