"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Icon = require("react-bootstrap-icons");
var SliderKart = function () {
    return (React.createElement("div", { className: "row" },
        React.createElement("div", { className: "col-md-12 mt-4" },
            React.createElement("div", { id: "KontrolTusuTetikle2", className: "carousel slide gununFirsatlariSlider", "data-bs-ride": "carousel", "data-bs-interval": "false" },
                React.createElement("div", { className: "carousel-inner" },
                    React.createElement("div", { className: "carousel-item active" },
                        React.createElement("div", { className: "card-group", id: "kartlar" },
                            React.createElement("div", { className: "card", id: "kart1" },
                                React.createElement("a", { href: "#", className: "btn text-start p-0" },
                                    React.createElement("div", { className: "card-header", style: { backgroundImage: " url(" + require('./SliderKartImg/48345076.jpg') + ")" } }),
                                    React.createElement("div", { className: "card-body" },
                                        React.createElement("p", { className: "card-text baslik" }, "Apple MacBook Air 13\" M1 8C CPU 256GB Space Grey MGN63TU/A"),
                                        React.createElement("span", { className: "card-text badge rounded-pill ikon" },
                                            "3.0",
                                            React.createElement(Icon.StarFill, null)),
                                        React.createElement("span", { className: "card-text badge ps-0 mt-2 indirimlifiyat" }, "9.599.00 TL"),
                                        React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "10.999.00 TL"),
                                        React.createElement("span", { className: "card-text badge fiyatfark" }, "1400 TL \u0130ndirim")))),
                            React.createElement("div", { className: "card", id: "kart2" },
                                React.createElement("a", { href: "#", className: "btn text-start p-0" },
                                    React.createElement("div", { className: "card-header", style: { backgroundImage: " url(" + require('./SliderKartImg/52999229.png') + ")" } }),
                                    React.createElement("div", { className: "card-body" },
                                        React.createElement("p", { className: "card-text baslik" }, "Samsung Galaxy A52 Ak\u0131ll\u0131 Telefon Beyaz"),
                                        React.createElement("span", { className: "card-text badge ps-0 indirimlifiyat" }, "3.899.00 TL"),
                                        React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "3.999.00 TL"),
                                        React.createElement("span", { className: "card-text badge fiyatfark" }, "100 TL \u0130ndirim")))),
                            React.createElement("div", { className: "card", id: "kart3" },
                                React.createElement("a", { href: "#", className: "btn text-start p-0" },
                                    React.createElement("div", { className: "card-header", style: { backgroundImage: " url(" + require('./SliderKartImg/52990132.png') + ")" } }),
                                    React.createElement("div", { className: "card-body" },
                                        React.createElement("p", { className: "card-text baslik" }, "Samsung Galaxy A32 Light Violet Ak\u0131ll\u0131 Telefon Light Violet"),
                                        React.createElement("span", { className: "card-text badge ps-0 indirimlifiyat" }, "3.599.00 TL")))),
                            React.createElement("div", { className: "card", id: "kart4" },
                                React.createElement("a", { href: "#", className: "btn text-start p-0" },
                                    React.createElement("div", { className: "card-header", style: { backgroundImage: " url(" + require('./SliderKartImg/46607432.jpg') + ")" } }),
                                    React.createElement("div", { className: "card-body" },
                                        React.createElement("p", { className: "card-text baslik" }, "Philips 55PUS7805/62 55\" 139 Ekran Ambilightl\u0131 4K UHD Smart TV"),
                                        React.createElement("span", { className: "card-text badge rounded-pill ikon" },
                                            "5.0",
                                            React.createElement(Icon.StarFill, null)),
                                        React.createElement("span", { className: "card-text badge ps-0 mt-2 indirimlifiyat" }, "9.599.00 TL"),
                                        React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "10.999.00 TL"),
                                        React.createElement("span", { className: "card-text badge fiyatfark" }, "1400 TL \u0130ndirim")))))),
                    React.createElement("div", { className: "carousel-item" },
                        React.createElement("div", { className: "card-group", id: "kartlar" },
                            React.createElement("div", { className: "card", id: "kart5" },
                                React.createElement("a", { href: "#", className: "btn text-start p-0" },
                                    React.createElement("div", { className: "card-header", style: { backgroundImage: " url(" + require('./SliderKartImg/yeni1.jpg') + ")" } }),
                                    React.createElement("div", { className: "card-body" },
                                        React.createElement("p", { className: "card-text baslik" }, "Philips XB9155/07 Marathon Ultimate Toz Torbas\u0131z S\u00FCp\u00FCrge"),
                                        React.createElement("span", { className: "card-text badge rounded-pill ikon" },
                                            "3.0",
                                            React.createElement(Icon.StarFill, null)),
                                        React.createElement("span", { className: "card-text badge ps-0 mt-2 indirimlifiyat" }, "3.499.00 TL"),
                                        React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "3.899.00 TL"),
                                        React.createElement("span", { className: "card-text badge fiyatfark" }, "400 TL \u0130ndirim")))),
                            React.createElement("div", { className: "card", id: "kart6" },
                                React.createElement("a", { href: "#", className: "btn text-start p-0" },
                                    React.createElement("div", { className: "card-header", style: { backgroundImage: " url(" + require('./SliderKartImg/yeni2.png') + ")" } }),
                                    React.createElement("div", { className: "card-body" },
                                        React.createElement("p", { className: "card-text baslik" }, "TCL 55C715 55\" 139 Ekran 4K UHD Android Smart QLED TV"),
                                        React.createElement("span", { className: "card-text badge ps-0 indirimlifiyat" }, "5.999.00 TL"),
                                        React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "6.999.00 TL"),
                                        React.createElement("span", { className: "card-text badge fiyatfark" }, "1000 TL \u0130ndirim")))),
                            React.createElement("div", { className: "card", id: "kart7" },
                                React.createElement("a", { href: "#", className: "btn text-start p-0" },
                                    React.createElement("div", { className: "card-header", style: { backgroundImage: " url(" + require('./SliderKartImg/yeni3.jpg') + ")" } }),
                                    React.createElement("div", { className: "card-body" },
                                        React.createElement("p", { className: "card-text baslik" }, "LG 65UN73006 65\" 165 Ekran 4K UHD Smart TV"),
                                        React.createElement("span", { className: "card-text badge ps-0 indirimlifiyat" }, "7.499.00 TL")))),
                            React.createElement("div", { className: "card", id: "kart8" },
                                React.createElement("a", { href: "#", className: "btn text-start p-0" },
                                    React.createElement("div", { className: "card-header", style: { backgroundImage: " url(" + require('./SliderKartImg/yeni4.jpg') + ")" } }),
                                    React.createElement("div", { className: "card-body" },
                                        React.createElement("p", { className: "card-text baslik" }, "Samsung WW90J5475FW/AH A+++ Enerji S\u0131n\u0131f\u0131 9 Kg 1400 Devir \u00C7ama\u015F\u0131r Makinesi"),
                                        React.createElement("span", { className: "card-text badge rounded-pill ikon" },
                                            "5.0",
                                            React.createElement(Icon.StarFill, null)),
                                        React.createElement("span", { className: "card-text badge ps-0 mt-2 indirimlifiyat" }, "3.399.00 TL"),
                                        React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "4.299.00 TL"),
                                        React.createElement("span", { className: "card-text badge fiyatfark" }, "900 TL \u0130ndirim"))))))),
                React.createElement("button", { id: "geri", className: "carousel-control-prev", "data-bs-target": "#KontrolTusuTetikle2", "data-bs-slide": "prev" },
                    React.createElement("span", null,
                        React.createElement(Icon.ArrowLeftCircleFill, null)),
                    React.createElement("span", { className: "visually-hidden" }, "Geri")),
                React.createElement("button", { id: "ileri", className: "carousel-control-next", "data-bs-target": "#KontrolTusuTetikle2", "data-bs-slide": "next" },
                    React.createElement("span", null,
                        React.createElement(Icon.ArrowRightCircleFill, null)),
                    React.createElement("span", { className: "visually-hidden" }, "\u0130leri"))),
            React.createElement("div", { className: "card-group d-none gizliKart", id: "kartlar" },
                React.createElement("div", { className: "card", id: "kart1" },
                    React.createElement("a", { href: "#", className: "btn text-start p-0" },
                        React.createElement("img", { className: "card-img-top img-fluid", src: require('./SliderKartImg/48345076.jpg') }),
                        React.createElement("div", { className: "card-body" },
                            React.createElement("p", { className: "card-text baslik" }, "Apple MacBook Air 13\" M1 8C CPU 256GB Space Grey MGN63TU/A"),
                            React.createElement("span", { className: "card-text badge rounded-pill ikon" },
                                "3.0 ",
                                React.createElement(Icon.StarFill, { viewBox: "1 1 17 17" })),
                            React.createElement("span", { className: "card-text badge ps-0 mt-2 indirimlifiyat" }, " 9.599.00 TL"),
                            React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "10.999.00 TL"),
                            React.createElement("span", { className: "card-text badge fiyatfark" }, "1400 TL \u0130ndirim")))),
                React.createElement("div", { className: "card", id: "kart2" },
                    React.createElement("a", { href: "#", className: "btn text-start p-0" },
                        React.createElement("img", { className: "card-img-top", src: require('./SliderKartImg/52999229.png') }),
                        React.createElement("div", { className: "card-body" },
                            React.createElement("p", { className: "card-text baslik" }, "Samsung Galaxy A52 Ak\u0131ll\u0131 Telefon Beyaz"),
                            React.createElement("span", { className: "card-text badge ps-0 indirimlifiyat" }, "3.899.00 TL"),
                            React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "3.999.00 TL"),
                            React.createElement("span", { className: "card-text badge fiyatfark" }, "100 TL \u0130ndirim")))),
                React.createElement("div", { className: "card", id: "kart3" },
                    React.createElement("a", { href: "#", className: "btn text-start p-0" },
                        React.createElement("img", { className: "card-img-top", src: require('./SliderKartImg/52990132.png') }),
                        React.createElement("div", { className: "card-body" },
                            React.createElement("p", { className: "card-text baslik" }, "Samsung Galaxy A32 Light Violet Ak\u0131ll\u0131 Telefon Light Violet"),
                            React.createElement("span", { className: "card-text badge ps-0 indirimlifiyat" }, "3.599.00 TL")))),
                React.createElement("div", { className: "card", id: "kart4" },
                    React.createElement("a", { href: "#", className: "btn text-start p-0" },
                        React.createElement("img", { className: "card-img-top", src: require('./SliderKartImg/46607432.jpg') }),
                        React.createElement("div", { className: "card-body mt-5" },
                            React.createElement("p", { className: "card-text baslik" }, "Philips 55PUS7805/62 55\" 139 Ekran Ambilightl\u0131 4K UHD Smart TV"),
                            React.createElement("span", { className: "card-text badge rounded-pill ikon" },
                                "5.0",
                                React.createElement(Icon.StarFill, { viewBox: "1 1 17 17" })),
                            React.createElement("span", { className: "card-text badge ps-0 mt-2 indirimlifiyat" }, "9.599.00 TL"),
                            React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "10.999.00 TL"),
                            React.createElement("span", { className: "card-text badge fiyatfark" }, "1400 TL \u0130ndirim")))),
                React.createElement("div", { className: "card", id: "kart5" },
                    React.createElement("a", { href: "#", className: "btn text-start p-0" },
                        React.createElement("img", { className: "card-img-top img-fluid", src: require('./SliderKartImg/yeni1.jpg') }),
                        React.createElement("div", { className: "card-body" },
                            React.createElement("p", { className: "card-text baslik" }, "Philips XB9155/07 Marathon Ultimate Toz Torbas\u0131z S\u00FCp\u00FCrge"),
                            React.createElement("span", { className: "card-text badge rounded-pill ikon" },
                                "3.0",
                                React.createElement(Icon.StarFill, { viewBox: "1 1 17 17" })),
                            React.createElement("span", { className: "card-text badge ps-0 mt-2 indirimlifiyat" }, "3.499.00 TL"),
                            React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "3.899.00 TL"),
                            React.createElement("span", { className: "card-text badge fiyatfark" }, "400 TL \u0130ndirim")))),
                React.createElement("div", { className: "card", id: "kart6" },
                    React.createElement("a", { href: "#", className: "btn text-start p-0" },
                        React.createElement("img", { className: "card-img-top", src: require('./SliderKartImg/yeni2.png') }),
                        React.createElement("div", { className: "card-body" },
                            React.createElement("p", { className: "card-text baslik" }, "TCL 55C715 55\" 139 Ekran 4K UHD Android Smart QLED TV"),
                            React.createElement("span", { className: "card-text badge ps-0 indirimlifiyat" }, "5.999.00 TL"),
                            React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "6.999.00 TL"),
                            React.createElement("span", { className: "card-text badge fiyatfark" }, "1000 TL \u0130ndirim")))),
                React.createElement("div", { className: "card", id: "kart7" },
                    React.createElement("a", { href: "#", className: "btn text-start p-0" },
                        React.createElement("img", { className: "card-img-top", src: require('./SliderKartImg/yeni3.jpg') }),
                        React.createElement("div", { className: "card-body" },
                            React.createElement("p", { className: "card-text baslik" }, "LG 65UN73006 65\" 165 Ekran 4K UHD Smart TV"),
                            React.createElement("span", { className: "card-text badge ps-0 indirimlifiyat" }, "7.499.00 TL")))),
                React.createElement("div", { className: "card", id: "kart8" },
                    React.createElement("a", { href: "#", className: "btn text-start p-0" },
                        React.createElement("img", { className: "card-img-top", src: require('./SliderKartImg/yeni4.jpg') }),
                        React.createElement("div", { className: "card-body mt-5" },
                            React.createElement("p", { className: "card-text baslik" }, "Samsung WW90J5475FW/AH A+++ Enerji S\u0131n\u0131f\u0131 9 Kg 1400 Devir \u00C7ama\u015F\u0131r Makinesi"),
                            React.createElement("span", { className: "card-text badge rounded-pill ikon" },
                                "5.0",
                                React.createElement(Icon.StarFill, { viewBox: "1 1 17 17" })),
                            React.createElement("span", { className: "card-text badge ps-0 mt-2 indirimlifiyat" }, "3.399.00 TL"),
                            React.createElement("span", { className: "card-text badge ps-0 asilfiyat" }, "4.299.00 TL"),
                            React.createElement("span", { className: "card-text badge fiyatfark" }, "900 TL \u0130ndirim"))))))));
};
exports.default = SliderKart;
//# sourceMappingURL=SliderKart.js.map