"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
require("./Slider.css");
var Slider = function () {
    return (React.createElement("div", { className: "col-md-12" },
        React.createElement("div", { id: "KontrolTusuTetikle1", className: "carousel slide slider1", "data-bs-ride": "carousel" },
            React.createElement("div", { className: "carousel-inner" },
                React.createElement("div", { id: "", className: "carousel-item active" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889424805938.jpg'), className: "d-block w-100 ", alt: "urun1" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889354092594.jpg'), className: "d-block w-100 ", alt: "urun2" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889322930226.jpg'), className: "d-block w-100 ", alt: "urun3" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889423855666.jpg'), className: "d-block w-100 ", alt: "urun4" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889301598258.jpg'), className: "d-block w-100 ", alt: "urun5" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889423659058.jpg'), className: "d-block w-100 ", alt: "urun6" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889353633842.jpg'), className: "d-block w-100 ", alt: "urun7" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8887515775026.jpg'), className: "d-block w-100 ", alt: "urun8" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889186975794.jpg'), className: "d-block w-100 ", alt: "urun9" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889326993458.jpg'), className: "d-block w-100 ", alt: "urun10" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889292652594.jpg'), className: "d-block w-100 ", alt: "urun11" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8888500551730.jpg'), className: "d-block w-100 ", alt: "urun12" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889326764082.jpg'), className: "d-block w-100 ", alt: "urun13" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889419399218.jpg'), className: "d-block w-100 ", alt: "urun14" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8887843684402.jpg'), className: "d-block w-100 ", alt: "urun15" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889451675698.jpg'), className: "d-block w-100 ", alt: "urun16" }))),
                React.createElement("div", { id: "", className: "carousel-item" },
                    React.createElement("a", { href: "#" },
                        " ",
                        React.createElement("img", { src: require('./SliderImg/8889323061298.jpg'), className: "d-block w-100 ", alt: "urun17" })))),
            React.createElement("div", { className: "col-md-12 d-none", id: "gostergeCubuklari" },
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "0", className: "active" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "1" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "2" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "3" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "4" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "5" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "6" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "7" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "8" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "9" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "10" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "11" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "12" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "13" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "14" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "15" }),
                React.createElement("input", { type: "button", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "16" })),
            React.createElement("div", { className: "col-md-12", id: "tuslar" },
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "0" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889424871474.jpg'), className: "d-block w-100", alt: "urun1tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "1" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889354158130.jpg'), className: "d-block w-100", alt: "urun2tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "2" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889291538482.jpg'), className: "d-block w-100", alt: "urun3tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "3" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889423921202.jpg'), className: "d-block w-100", alt: "urun4tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "4" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889301729330.jpg'), className: "d-block w-100", alt: "urun5tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "5" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889423724594.jpg'), className: "d-block w-100", alt: "urun6tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "6" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889353764914.jpg'), className: "d-block w-100", alt: "urun7tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "7" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8887548575794.jpg'), className: "d-block w-100", alt: "urun8tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "8" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889186943026.jpg'), className: "d-block w-100", alt: "urun9tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "9" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889326927922.jpg'), className: "d-block w-100", alt: "urun10tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "10" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889292685362.jpg'), className: "d-block w-100", alt: "urun11tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "11" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8888500617266.jpg'), className: "d-block w-100", alt: "urun12tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "12" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889325125682.jpg'), className: "d-block w-100", alt: "urun13tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "13" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889419464754.jpg'), className: "d-block w-100", alt: "urun14tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "14" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889325125682.jpg'), className: "d-block w-100", alt: "urun15tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "15" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889451708466.jpg'), className: "d-block w-100", alt: "urun16tus" })),
                React.createElement("button", { id: "", "data-bs-target": "#KontrolTusuTetikle1", "data-bs-slide-to": "16" },
                    React.createElement("img", { src: require('./SliderImg/sliderTus/8889323126834.jpg'), className: "d-block w-100", alt: "urun17tus" }))))));
};
exports.default = Slider;
//# sourceMappingURL=Slider.js.map